Repository GSG-G10/team6-news-project, pull requests merged in 2021-07, with the labels that each got.

#4 Home page header & navbar
  home-page/style.css
  index.html
  index.js
Labels: Changes Requested

#5 Home page content sections
  home-page/style.css
  images/home/avatar.png
  images/home/background-showcase.jpg
  images/home/new1.jpg
  images/home/new2.jpg
  images/home/new3.jpg
  images/home/new4.jpg
  index.html
Labels: done

#8 add footer section for home page
  home-page/style.css
  index.html
Labels: done

#6 Created comment sections in HTML and CSS & the footer included
  README.md
  blog.css
  blog.html
Labels: waiting review

#10 edit link in showcase
  index.html
Labels: done

#25 update website
  blog.html
  index.html
Labels: in-progress
